### ISSUE TITLE
syntax error, unexpected end-of-input, expecting end

### ISSUE THREAD

**Issue by moonlight4617** [moonlight4617/tempo#3]
class ShopsController < ApplicationController
      before_action :set_shop, only: [:show, :edit, :update, :destroy, :completely_destroy]
      before_action :set_owner, only: [:create, :show]
      before_action :before_login_owner, only: [:new, :create, :edit, :update, :destroy]
      before_action :correct_owner, only: [:edit, :update, :destroy]
    
    def index
      @shops = Shop.all
    end
  
    def new
      @shop = Shop.new
    end
  
    def create
      set_business_time
      binding.pry
      
      @shop = @owner.shops.create(shop_params) 
      @shop.business_time = business_time
      if @shop.save
        redirect_to s_show_path(@shop)
      else
        render 'new'
      end
    end
  
    def show
      @owner = @shop.owner
    end
  
    def edit
    end
  
    def update
      set_business_time
     binding.pry
      if @shop.update(shop_params)
        redirect_to s_show_path(@shop)
      else
        render 'edit'
      end
    end
  
    def destroy
      @shop.del_flg = 1
      @shop.save
      redirect_to s_index_path
    end
  
    def zip
      p params
    end
  
    def set_business_time
  
    end
  
    def create_business_time
      
    end
  
    private
  
      def shop_params
        params.require(:shop).permit(:name, :prefecture, :city, :address, :tel, :station, :capacity, :image, :price, :content, :zip_code, :start_time, :end_time)
      end
  
      def set_shop
        @shop = Shop.find_by(id: params[:id])
      end
  
      def set_owner
        @owner = Owner.find_by(id: session[:owner_id])
      end
  
      def correct_owner
        set_shop
        set_owner
        if @shop.owner != @owner
          redirect_to root_path
        end
      end
  
      def set_business_time
        s_time = params[:shop][:start_time]
        e_time = params[:shop][:end_time]
        @business_time = []  
        i = s_time
        while i <= e_time do
          business_time.push(i)
          i ++
        end     
        @shop.business_time = business_time
      end
  end

**Comment by good1luck21** [comment]
お疲れ様です！
こういう時は全体で見るよりも1つのRubyのメソッドとしてどっかのファイルとかに書いて実行してみると、
何がいけないのかわかりやすくなります！
今回の結論としては`i ++`の部分です！

```ruby
def set_business_time
  s_time = 9
  e_time = 18
  business_time = []
  i = s_time
  while i <= e_time do
    business_time.push(i)
    i = i + 1
  end
  puts business_time
end

set_business_time
```

上記のように`i = i + 1`に変更すると想定している結果が出ると思います！
https://drive.google.com/drive/folders/19HeGSv5z9EQa1E5YW5cWRazWtSbzZbw5?usp=sharing
上記ドライブに僕が実行したファイル入れときますので、試してみてください！

宜しくお願いします！
